let tasks = [
  {
    id: 1,
    titulo: "Diseñar la base de datos",
    descripcion: "Modelo relacional para el sistema",
    fecha_inicio: "2025-09-01",
    fecha_fin: "2025-09-05",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 1,
    usuario_asignado_id: 1,
  },
  {
    id: 2,
    titulo: "Configurar CI/CD",
    descripcion: "Pipeline en GitHub Actions",
    fecha_inicio: "2025-09-03",
    fecha_fin: "2025-09-07",
    estado: "en_progreso",
    prioridad: "media",
    proyecto_id: 1,
    usuario_asignado_id: 2,
  },
  {
    id: 3,
    titulo: "Diseño de interfaz",
    descripcion: "Mockups en Figma",
    fecha_inicio: "2025-09-02",
    fecha_fin: "2025-09-06",
    estado: "completada",
    prioridad: "baja",
    proyecto_id: 2,
    usuario_asignado_id: 3,
  },
  {
    id: 4,
    titulo: "Revisión de seguridad",
    descripcion: "Pruebas de vulnerabilidades OWASP",
    fecha_inicio: "2025-09-08",
    fecha_fin: "2025-09-12",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 3,
    usuario_asignado_id: 4,
  },
  {
    id: 5,
    titulo: "Integración con pasarela de pagos",
    descripcion: "Stripe y PayPal",
    fecha_inicio: "2025-09-05",
    fecha_fin: "2025-09-15",
    estado: "en_progreso",
    prioridad: "alta",
    proyecto_id: 4,
    usuario_asignado_id: 2,
  },
  {
    id: 6,
    titulo: "Migración de datos",
    descripcion: "Migrar datos desde el sistema antiguo",
    fecha_inicio: "2025-09-10",
    fecha_fin: "2025-09-20",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 5,
    usuario_asignado_id: 5,
  },
  {
    id: 7,
    titulo: "Pruebas unitarias",
    descripcion: "Cobertura mínima del 80%",
    fecha_inicio: "2025-09-01",
    fecha_fin: "2025-09-08",
    estado: "completada",
    prioridad: "baja",
    proyecto_id: 6,
    usuario_asignado_id: 6,
  },
  {
    id: 8,
    titulo: "Optimización de rendimiento",
    descripcion: "Reducir tiempo de carga a <2s",
    fecha_inicio: "2025-09-07",
    fecha_fin: "2025-09-14",
    estado: "en_progreso",
    prioridad: "alta",
    proyecto_id: 7,
    usuario_asignado_id: 3,
  },
  {
    id: 9,
    titulo: "Implementar notificaciones push",
    descripcion: "Soporte para navegadores y móvil",
    fecha_inicio: "2025-09-12",
    fecha_fin: "2025-09-18",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 8,
    usuario_asignado_id: 7,
  },
  {
    id: 10,
    titulo: "Configurar balanceador de carga",
    descripcion: "NGINX y HAProxy",
    fecha_inicio: "2025-09-15",
    fecha_fin: "2025-09-22",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 9,
    usuario_asignado_id: 8,
  },
  {
    id: 11,
    titulo: "Monitoreo del sistema",
    descripcion: "Implementar Grafana y Prometheus",
    fecha_inicio: "2025-09-01",
    fecha_fin: "2025-09-10",
    estado: "en_progreso",
    prioridad: "media",
    proyecto_id: 10,
    usuario_asignado_id: 1,
  },
  {
    id: 12,
    titulo: "Diseñar landing page",
    descripcion: "HTML + CSS responsivo",
    fecha_inicio: "2025-09-04",
    fecha_fin: "2025-09-08",
    estado: "completada",
    prioridad: "baja",
    proyecto_id: 11,
    usuario_asignado_id: 9,
  },
  {
    id: 13,
    titulo: "Analizar logs",
    descripcion: "Sistema de auditoría de usuarios",
    fecha_inicio: "2025-09-06",
    fecha_fin: "2025-09-11",
    estado: "en_progreso",
    prioridad: "alta",
    proyecto_id: 12,
    usuario_asignado_id: 10,
  },
  {
    id: 14,
    titulo: "Soporte multilenguaje",
    descripcion: "Traducciones con i18n",
    fecha_inicio: "2025-09-03",
    fecha_fin: "2025-09-09",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 8,
    usuario_asignado_id: 11,
  },
  {
    id: 15,
    titulo: "Configurar backup automático",
    descripcion: "Copias en S3 cada 24h",
    fecha_inicio: "2025-09-09",
    fecha_fin: "2025-09-15",
    estado: "en_progreso",
    prioridad: "alta",
    proyecto_id: 6,
    usuario_asignado_id: 12,
  },
  {
    id: 16,
    titulo: "Implementar autenticación 2FA",
    descripcion: "Google Authenticator",
    fecha_inicio: "2025-09-13",
    fecha_fin: "2025-09-19",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 3,
    usuario_asignado_id: 13,
  },
  {
    id: 17,
    titulo: "Revisión de accesibilidad",
    descripcion: "Cumplir WCAG 2.1 AA",
    fecha_inicio: "2025-09-05",
    fecha_fin: "2025-09-12",
    estado: "completada",
    prioridad: "media",
    proyecto_id: 5,
    usuario_asignado_id: 14,
  },
  {
    id: 18,
    titulo: "Documentación de API",
    descripcion: "Swagger/OpenAPI",
    fecha_inicio: "2025-09-07",
    fecha_fin: "2025-09-13",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 2,
    usuario_asignado_id: 15,
  },
  {
    id: 19,
    titulo: "Implementar chat en tiempo real",
    descripcion: "WebSockets + Redis",
    fecha_inicio: "2025-09-02",
    fecha_fin: "2025-09-09",
    estado: "en_progreso",
    prioridad: "alta",
    proyecto_id: 11,
    usuario_asignado_id: 16,
  },
  {
    id: 20,
    titulo: "Mejorar SEO",
    descripcion: "Optimización para buscadores",
    fecha_inicio: "2025-09-01",
    fecha_fin: "2025-09-07",
    estado: "completada",
    prioridad: "baja",
    proyecto_id: 4,
    usuario_asignado_id: 17,
  },
];

export default {
  getAllTasks: async () => ({ tasks }),

  createTask: async (data) => {
    const newTask = { id: tasks.length + 1, ...data };
    tasks.push(newTask);
    return newTask;
  },

  updateTask: async (id, data) => {
    const index = tasks.findIndex((t) => t.id === id);
    if (index !== -1) {
      tasks[index] = { ...tasks[index], ...data };
      return tasks[index];
    }
    throw new Error("Tarea no encontrada");
  },

  deleteTask: async (id) => {
    tasks = tasks.filter((t) => t.id !== id);
    return { success: true };
  },
};
