let tasks = [
  // Proyecto 1
  {
    id: 1,
    titulo: "Diseñar la base de datos",
    descripcion: "Modelo relacional para el sistema de ventas",
    fecha_inicio: "2025-09-01",
    fecha_fin: "2025-09-05",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 1,
    usuario_asignado_id: 1,
  },
  {
    id: 2,
    titulo: "Configurar CI/CD",
    descripcion: "Pipeline en GitHub Actions",
    fecha_inicio: "2025-09-03",
    fecha_fin: "2025-09-07",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 1,
    usuario_asignado_id: 2,
  },
  {
    id: 3,
    titulo: "Pruebas unitarias módulo ventas",
    descripcion: "Cobertura mínima 80%",
    fecha_inicio: "2025-09-04",
    fecha_fin: "2025-09-10",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 1,
    usuario_asignado_id: 3,
  },
  {
    id: 4,
    titulo: "Revisión de seguridad",
    descripcion: "Auditoría inicial",
    fecha_inicio: "2025-09-12",
    fecha_fin: "2025-09-18",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 1,
    usuario_asignado_id: 4,
  },
  {
    id: 5,
    titulo: "Documentación API ventas",
    descripcion: "Swagger/OpenAPI",
    fecha_inicio: "2025-09-11",
    fecha_fin: "2025-09-13",
    estado: "completada",
    prioridad: "baja",
    proyecto_id: 1,
    usuario_asignado_id: 5,
  },
  {
    id: 6,
    titulo: "Optimización de consultas SQL",
    descripcion: "Mejorar tiempos de respuesta en reportes",
    fecha_inicio: "2025-09-19",
    fecha_fin: "2025-09-25",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 1,
    usuario_asignado_id: 6,
  },
  {
    id: 7,
    titulo: "Reunión con stakeholders",
    descripcion: "Definir alcance del módulo ventas",
    fecha_inicio: "2025-09-08",
    fecha_fin: "2025-09-08",
    estado: "pendiente",
    prioridad: "baja",
    proyecto_id: 1,
    usuario_asignado_id: 7,
  },
  {
    id: 8,
    titulo: "Migración a servidor de pruebas",
    descripcion: "Subir versión inicial al ambiente staging",
    fecha_inicio: "2025-09-20",
    fecha_fin: "2025-09-22",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 1,
    usuario_asignado_id: 8,
  },

  // Proyecto 2
  {
    id: 9,
    titulo: "Diseño de interfaz",
    descripcion: "Mockups en Figma",
    fecha_inicio: "2025-09-02",
    fecha_fin: "2025-09-06",
    estado: "completada",
    prioridad: "baja",
    proyecto_id: 2,
    usuario_asignado_id: 9,
  },
  {
    id: 10,
    titulo: "API de empleados",
    descripcion: "CRUD para gestión de RRHH",
    fecha_inicio: "2025-09-05",
    fecha_fin: "2025-09-12",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 2,
    usuario_asignado_id: 10,
  },
  {
    id: 11,
    titulo: "Integración con nómina",
    descripcion: "Sincronización con sistema externo",
    fecha_inicio: "2025-09-07",
    fecha_fin: "2025-09-15",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 2,
    usuario_asignado_id: 11,
  },
  {
    id: 12,
    titulo: "Dashboard de RRHH",
    descripcion: "Pantalla principal con métricas",
    fecha_inicio: "2025-09-13",
    fecha_fin: "2025-09-20",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 2,
    usuario_asignado_id: 12,
  },
  {
    id: 13,
    titulo: "Control de permisos",
    descripcion: "Roles: admin, gestor, empleado",
    fecha_inicio: "2025-09-14",
    fecha_fin: "2025-09-21",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 2,
    usuario_asignado_id: 13,
  },
  {
    id: 14,
    titulo: "Reporte de vacaciones",
    descripcion: "Generar informe mensual en PDF",
    fecha_inicio: "2025-09-18",
    fecha_fin: "2025-09-24",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 2,
    usuario_asignado_id: 14,
  },
  {
    id: 15,
    titulo: "Testing módulo nómina",
    descripcion: "Cobertura mínima 70%",
    fecha_inicio: "2025-09-22",
    fecha_fin: "2025-09-28",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 2,
    usuario_asignado_id: 15,
  },
  {
    id: 16,
    titulo: "Soporte legal",
    descripcion: "Revisión cumplimiento normativo",
    fecha_inicio: "2025-09-25",
    fecha_fin: "2025-09-29",
    estado: "pendiente",
    prioridad: "baja",
    proyecto_id: 2,
    usuario_asignado_id: 16,
  },

  // Proyecto 3
  {
    id: 17,
    titulo: "Login con OAuth",
    descripcion: "Autenticación con Google y Facebook",
    fecha_inicio: "2025-09-08",
    fecha_fin: "2025-09-12",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 3,
    usuario_asignado_id: 17,
  },
  {
    id: 18,
    titulo: "Notificaciones push",
    descripcion: "Envío de alertas en tiempo real",
    fecha_inicio: "2025-09-09",
    fecha_fin: "2025-09-16",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 3,
    usuario_asignado_id: 18,
  },
  {
    id: 19,
    titulo: "Optimización de rendimiento",
    descripcion: "Mejorar tiempos de carga",
    fecha_inicio: "2025-09-10",
    fecha_fin: "2025-09-20",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 3,
    usuario_asignado_id: 19,
  },
  {
    id: 20,
    titulo: "Módulo de reportes",
    descripcion: "Generar PDF y Excel",
    fecha_inicio: "2025-09-15",
    fecha_fin: "2025-09-25",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 3,
    usuario_asignado_id: 20,
  },
  {
    id: 21,
    titulo: "Testing de UI",
    descripcion: "Pruebas automáticas con Cypress",
    fecha_inicio: "2025-09-16",
    fecha_fin: "2025-09-22",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 3,
    usuario_asignado_id: 21,
  },
  {
    id: 22,
    titulo: "Optimización de imágenes",
    descripcion: "Reducir peso sin perder calidad",
    fecha_inicio: "2025-09-18",
    fecha_fin: "2025-09-21",
    estado: "pendiente",
    prioridad: "baja",
    proyecto_id: 3,
    usuario_asignado_id: 22,
  },
  {
    id: 23,
    titulo: "Revisión accesibilidad",
    descripcion: "Cumplir WCAG nivel AA",
    fecha_inicio: "2025-09-23",
    fecha_fin: "2025-09-29",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 3,
    usuario_asignado_id: 23,
  },
  {
    id: 24,
    titulo: "Optimización API",
    descripcion: "Reducir tiempos de respuesta a < 200ms",
    fecha_inicio: "2025-09-25",
    fecha_fin: "2025-09-30",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 3,
    usuario_asignado_id: 24,
  },

  // Proyecto 4
  {
    id: 25,
    titulo: "Migración de base de datos",
    descripcion: "De MySQL a PostgreSQL",
    fecha_inicio: "2025-09-17",
    fecha_fin: "2025-09-25",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 4,
    usuario_asignado_id: 25,
  },
  {
    id: 26,
    titulo: "Configuración Docker",
    descripcion: "Containers para backend y frontend",
    fecha_inicio: "2025-09-18",
    fecha_fin: "2025-09-23",
    estado: "completada",
    prioridad: "alta",
    proyecto_id: 4,
    usuario_asignado_id: 26,
  },
  {
    id: 27,
    titulo: "Integración API externa",
    descripcion: "Servicio de terceros para pagos",
    fecha_inicio: "2025-09-19",
    fecha_fin: "2025-09-27",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 4,
    usuario_asignado_id: 27,
  },
  {
    id: 28,
    titulo: "Revisión de logs",
    descripcion: "Configurar monitoreo con ELK",
    fecha_inicio: "2025-09-20",
    fecha_fin: "2025-09-25",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 4,
    usuario_asignado_id: 28,
  },
  {
    id: 29,
    titulo: "Backup automatizado",
    descripcion: "Scripts de respaldo diario",
    fecha_inicio: "2025-09-21",
    fecha_fin: "2025-09-24",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 4,
    usuario_asignado_id: 29,
  },
  {
    id: 30,
    titulo: "Revisión de seguridad en red",
    descripcion: "Configurar firewall y VPN",
    fecha_inicio: "2025-09-23",
    fecha_fin: "2025-09-27",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 4,
    usuario_asignado_id: 30,
  },
  {
    id: 31,
    titulo: "Pruebas de escalabilidad",
    descripcion: "Simulación con JMeter",
    fecha_inicio: "2025-09-25",
    fecha_fin: "2025-09-29",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 4,
    usuario_asignado_id: 31,
  },
  {
    id: 32,
    titulo: "Optimizar queries PostgreSQL",
    descripcion: "Añadir índices y optimizar consultas",
    fecha_inicio: "2025-09-27",
    fecha_fin: "2025-09-30",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 4,
    usuario_asignado_id: 32,
  },

  // Proyecto 5
  {
    id: 33,
    titulo: "Definición de KPIs",
    descripcion: "Indicadores clave del sistema",
    fecha_inicio: "2025-09-20",
    fecha_fin: "2025-09-24",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 5,
    usuario_asignado_id: 33,
  },
  {
    id: 34,
    titulo: "Soporte multi-idioma",
    descripcion: "Traducciones en i18n",
    fecha_inicio: "2025-09-21",
    fecha_fin: "2025-09-30",
    estado: "pendiente",
    prioridad: "baja",
    proyecto_id: 5,
    usuario_asignado_id: 34,
  },
  {
    id: 35,
    titulo: "Monitoreo de KPIs",
    descripcion: "Dashboard con métricas en tiempo real",
    fecha_inicio: "2025-09-22",
    fecha_fin: "2025-09-28",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 5,
    usuario_asignado_id: 35,
  },
  {
    id: 36,
    titulo: "Pruebas de usabilidad",
    descripcion: "Sesiones con usuarios reales",
    fecha_inicio: "2025-09-23",
    fecha_fin: "2025-09-27",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 5,
    usuario_asignado_id: 36,
  },
  {
    id: 37,
    titulo: "Optimización de rendimiento web",
    descripcion: "Reducir TTFB y mejorar Lighthouse",
    fecha_inicio: "2025-09-25",
    fecha_fin: "2025-09-29",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 5,
    usuario_asignado_id: 37,
  },
  {
    id: 38,
    titulo: "Reporte de incidencias",
    descripcion: "Sistema de tickets",
    fecha_inicio: "2025-09-26",
    fecha_fin: "2025-09-30",
    estado: "pendiente",
    prioridad: "media",
    proyecto_id: 5,
    usuario_asignado_id: 38,
  },
  {
    id: 39,
    titulo: "Integración con CRM",
    descripcion: "Sincronización de clientes",
    fecha_inicio: "2025-09-28",
    fecha_fin: "2025-10-02",
    estado: "pendiente",
    prioridad: "alta",
    proyecto_id: 5,
    usuario_asignado_id: 39,
  },
  {
    id: 40,
    titulo: "Backup de métricas",
    descripcion: "Guardar reportes históricos",
    fecha_inicio: "2025-09-29",
    fecha_fin: "2025-10-05",
    estado: "pendiente",
    prioridad: "baja",
    proyecto_id: 5,
    usuario_asignado_id: 40,
  },
];

export default {
  getAllTasks: async () => ({ tasks }),

  createTask: async (data) => {
    const newTask = { id: tasks.length + 1, ...data };
    tasks.push(newTask);
    return newTask;
  },

  updateTask: async (id, data) => {
    const index = tasks.findIndex((t) => t.id === id);
    if (index !== -1) {
      tasks[index] = { ...tasks[index], ...data };
      return tasks[index];
    }
    throw new Error("Tarea no encontrada");
  },

  deleteTask: async (id) => {
    tasks = tasks.filter((t) => t.id !== id);
    return { success: true };
  },
};
